-- ============================================================
-- Migration 0004: Data API grants (least privilege)
--
-- WHY: the project was created with "Automatically expose new tables"
-- DISABLED, so Supabase applied no default table privileges. Migrations
-- 0001-0003 created tables, triggers and RLS policies but no table GRANTs,
-- producing "permission denied for table content_entries" on first read.
--
-- MODEL: SQL privileges are the OUTER CEILING (which verbs a role may even
-- attempt); RLS policies remain the row-level authority inside that ceiling.
-- Nothing here disables or weakens any policy. Every grant below maps to a
-- concrete query in web/lib, web/app, or the seed/verification scripts.
-- INSERT/UPDATE are column-scoped where the application writes specific
-- columns. Verbs used only by SECURITY DEFINER trigger functions (e.g.
-- content_revisions INSERT, audit_logs INSERT) need NO grants: those run as
-- the function owner.
-- ============================================================

-- ---------- Defensive baseline ----------
-- No implicit privileges for PUBLIC on our tables, and no object creation.
revoke all on all tables in schema public from public;
revoke create on schema public from public;

-- All three Data API roles need schema visibility (idempotent if present).
grant usage on schema public to anon, authenticated, service_role;

-- Version-control-safe DEFAULT privileges: objects created in future
-- migrations (as the postgres role) get NO automatic exposure to the Data API
-- roles or PUBLIC. Every future table/function/sequence must be granted
-- explicitly in its own migration, and a fresh project behaves safely even if
-- the Dashboard's default-exposure setting differs.
alter default privileges for role postgres in schema public
  revoke select, insert, update, delete on tables
  from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke execute on functions
  from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke usage, select on sequences
  from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke execute on functions
  from public;

-- ============================================================
-- anon (public visitors via publishable key, incl. /api/lead server client)
-- ============================================================

-- Public site pages read approved content (RLS: content_select_public).
grant select on table public.content_entries to anon;

-- Lead submission backstop (RLS: leads_insert_public pins status/assigned_to/
-- consent). Column list = exactly what /api/lead inserts; id is generated by
-- the endpoint because anon has no SELECT (no RETURNING possible - by design).
grant insert (id, name, email, company, enquiry_type, message, source_page, consent, consent_text)
  on table public.leads to anon;

-- Deliberately NOT granted to anon: any SELECT on leads/lead_notes/profiles/
-- staff_roles/content_revisions/audit_logs, and any UPDATE/DELETE anywhere.

-- ============================================================
-- authenticated (staff sessions via publishable key + cookies; RLS scopes rows)
-- ============================================================

-- lib/auth.ts getStaffContext(): own roles + own profile display_name;
-- /admin/leads and /admin/users list profiles for assignment/role UI
-- (RLS: profiles_select_own_or_staff).
grant select on table public.profiles to authenticated;

-- Own-roles lookup + admin role management UI
-- (RLS: select own-or-admin; INSERT/DELETE policies enforce who may grant
-- what - administrators are limited to basic roles by WITH CHECK).
grant select on table public.staff_roles to authenticated;
grant insert (user_id, role, granted_by) on table public.staff_roles to authenticated;
grant delete on table public.staff_roles to authenticated;

-- Content: editor screen updates `value` only (version/updated_by/updated_at
-- are set by trigger); reads used by admin editor + RLS verification
-- (RLS: content_update_editors / content_select_public).
grant select on table public.content_entries to authenticated;
grant update (value) on table public.content_entries to authenticated;

-- Revision history is staff-visible (RLS restricts to editors/admins).
grant select on table public.content_revisions to authenticated;

-- Leads workbench: staff read (RLS: leads_select_staff); updates touch ONLY
-- status/assigned_to (immutability trigger + sales/admin UPDATE policies
-- enforce the approved assignment rules).
grant select on table public.leads to authenticated;
grant update (status, assigned_to) on table public.leads to authenticated;

-- Lead notes: append-only thread (RLS: sales only on own leads; admins any).
grant select on table public.lead_notes to authenticated;
grant insert (lead_id, author_id, body) on table public.lead_notes to authenticated;

-- Audit log viewer (RLS: audit_logs_select_admin -> admins/supers see rows,
-- other staff get zero rows, exactly what the verification script asserts).
grant select on table public.audit_logs to authenticated;

-- Deliberately NOT granted to authenticated (policies would allow some, but
-- the existing application never performs them - grant when a feature needs it):
--   leads INSERT            (public form always submits through the anon path)
--   content_entries INSERT  (new keys are seeded via service_role only)
--   profiles UPDATE         (no profile-edit UI yet)
--   any DELETE besides staff_roles (leads/notes/revisions/audit are append-only)

-- ============================================================
-- service_role (SUPABASE_SECRET_KEY - local seed/verification scripts only;
-- never used in request paths or browsers; has bypassrls, so grants are the
-- only ceiling that applies to it)
-- ============================================================

-- scripts/seed-content.ts: upsert + self-verification of the 8 content keys.
grant select on table public.content_entries to service_role;
grant insert (key, value) on table public.content_entries to service_role;
grant update (value) on table public.content_entries to service_role;

-- scripts/verify-rls.ts: grants roles to disposable test users during setup.
grant insert (user_id, role, granted_by) on table public.staff_roles to service_role;

-- scripts/verify-rls.ts: deletes ONLY the test leads it created (cleanup);
-- SELECT is required to evaluate the WHERE clause of those deletes.
grant select, delete on table public.leads to service_role;

-- Deliberately NOT granted to service_role: everything else. Test-user
-- removal goes through the Auth Admin API (auth schema) and cascades to
-- profiles/staff_roles/lead_notes without needing public-schema privileges.

-- ============================================================
-- Function EXECUTE (re-assert critical boundaries; idempotent with 0002)
-- ============================================================

-- Policy helpers must be callable by both API roles (they only report the
-- caller's own membership).
grant execute on function public.has_any_role(public.staff_role[]) to anon, authenticated;
grant execute on function public.is_staff() to anon, authenticated;

-- The one-time bootstrap stays unavailable to API roles: Dashboard SQL editor
-- (postgres) only. Re-asserted here in case of drift.
revoke execute on function public.bootstrap_first_super_admin(text) from public, anon, authenticated;

-- ============================================================
-- RLS remains ENABLED and unchanged on all seven tables (assertion only -
-- these are no-ops that fail loudly if someone disabled RLS out of band).
-- ============================================================
do $$
declare
  t text;
begin
  foreach t in array array['profiles','staff_roles','content_entries','content_revisions','leads','lead_notes','audit_logs']
  loop
    if not exists (
      select 1 from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'public' and c.relname = t and c.relrowsecurity
    ) then
      raise exception 'RLS is not enabled on public.% - refusing to apply grants', t;
    end if;
  end loop;
end $$;
